name: CI - Test Cucumber

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Start server
        run: npm start &
        env:
          NODE_ENV: test

      - name: Run BDD (Cucumber) tests
        run: npm run test-cucumber
        timeout-minutes: 15
